export const timers = [
    {
        timerName: "Morning Alarm",
        currentTime: 15 * 60,
        initialTime: 900,
        timerId: "timer-1",
        timerEventList: ["event-1", "event-2"],
        timerTriggerList: ["trigger-1", "trigger-2"],
        timerStartDate: "01/01/2025",
        timerStartTime: "12:00:00",
        timerEndDate: "01/01/2025",
        timerEndTime: "12:30:00",
        isPaused: true,
        isActive: true,
        isSet: true,
        isRunning: true,
        isStopped: true,
        isReset: true,
        isStarted: true,
        isFinished: true,
        isCompleted: true,
    },
    {
        timerName: "Evening Alarm",
        currentTime: 7200,
        initialTime: 900,
        timerId: "timer-3",
        timerEventList: ["event-3", "event-4"],
        timerTriggerList: ["trigger-3", "trigger-4"],
        timerStartDate: "01/01/2025",
        timerStartTime: "18:00:00",
        timerEndDate: "01/01/2025",
        timerEndTime: "18:30:00",
        isPaused: false,
        isActive: false,
        isSet: false,
        isRunning: false,
        isStopped: false,
        isReset: false,
        isStarted: false,
        isFinished: false,
        isCompleted: false,
    },
    {
        timerName: "Evening Alarm",
        currentTime: 7200,
        initialTime: 900,
        timerId: "timer-30",
        timerEventList: ["event-3", "event-4"],
        timerTriggerList: ["trigger-3", "trigger-4"],
        timerStartDate: "01/01/2025",
        timerStartTime: "18:00:00",
        timerEndDate: "01/01/2025",
        timerEndTime: "18:30:00",
        isPaused: false,
        isActive: false,
        isSet: false,
        isRunning: false,
        isStopped: false,
        isReset: false,
        isStarted: false,
        isFinished: false,
        isCompleted: false,
    },
    {
        timerName: "Evening Alarm",
        currentTime: 7200,
        initialTime: 900,
        timerId: "timer-4",
        timerEventList: ["event-3", "event-4"],
        timerTriggerList: ["trigger-3", "trigger-4"],
        timerStartDate: "01/01/2025",
        timerStartTime: "18:00:00",
        timerEndDate: "01/01/2025",
        timerEndTime: "18:30:00",
        isPaused: false,
        isActive: false,
        isSet: false,
        isRunning: false,
        isStopped: false,
        isReset: false,
        isStarted: false,
        isFinished: false,
        isCompleted: false,
    },
    {
        timerName: "Evening Alarm",
        currentTime: 7200,
        initialTime: 900,
        timerId: "timer-44",
        timerEventList: ["event-3", "event-4"],
        timerTriggerList: ["trigger-3", "trigger-4"],
        timerStartDate: "01/01/2025",
        timerStartTime: "18:00:00",
        timerEndDate: "01/01/2025",
        timerEndTime: "18:30:00",
        isPaused: false,
        isActive: false,
        isSet: false,
        isRunning: false,
        isStopped: false,
        isReset: false,
        isStarted: false,
        isFinished: false,
        isCompleted: false,
    },
    {
        timerName: "Evening Alarm",
        currentTime: 7200,
        initialTime: 900,
        timerId: "timer-45",
        timerEventList: ["event-3", "event-4"],
        timerTriggerList: ["trigger-3", "trigger-4"],
        timerStartDate: "01/01/2025",
        timerStartTime: "18:00:00",
        timerEndDate: "01/01/2025",
        timerEndTime: "18:30:00",
        isPaused: false,
        isActive: false,
        isSet: false,
        isRunning: false,
        isStopped: false,
        isReset: false,
        isStarted: false,
        isFinished: false,
        isCompleted: false,
    },
];

 
 export const timerItem = timers[0];
 export type TimerType = typeof timerItem;